[project]
name = "whiteglove"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "agentstack>=0.2.3",
    "tomli>=2.2.1",
]
