data_collector:
  role: >
    collect data
  goal: >
    read data from a pdf file to markdown

  backstory: >
    Your are a data collector
  # llm: openai/gpt-4o-mini
  llm: ollama/gpt-3.5-turbo

data_analyzer:
  role: >-
    Analyze markdowndata and find relevant information 
  goal: >-
    get Company name, plan name, base charge and energy charge from Electricity Facts Label
  backstory: >-
    You like to read Electricity Facts Label and find relevant data
  llm: ollama/gpt-3.5-turbo

# data_writer:
#   role: >-
#     write data 
#   goal: >-
#     write data to .csv file
#   backstory: >-
#     You like to log entries
#   llm: openai/gpt-3
