data_collector:
  role: >
    collect data
  goal: >
    find Electricity Facts Label from a website

  backstory: >
    Your are a data collector
  # llm: openai/gpt-4o-mini
  # llm: gpt-3.5-turbo
  llm: openai/gpt-3

data_analyzer:
  role: >-
    Analyze markdowndata and find relevant information 
  goal: >-
    get Company name, plan name, base charge and energy charge from Electricity Facts Label
  backstory: >-
    You like to read Electricity Facts Label and find relevant data
  llm: openai/gpt-3
data_writer:
  role: >-
    write data 
  goal: >-
    write data to .csv file
  backstory: >-
    You like to log entries
  llm: openai/gpt-3
