read_pdf:
  description: >-
     Read the following files in the "D:\Projects\WhiteGlove\data_processing\src\files" folder:
      - efl1.pdf
      - efl2.pdf
      Extract the company name, plan name, base charge, and energy charge, and write them to a data.csv file and store it in "D:\Projects\WhiteGlove\data_processing\src\output" folder.

  expected_output: >-
    data.csv files with columns id, company name, plan name,  base charge and energy charge
    and saved in "D:\Projects\WhiteGlove\data_processing\src\output" folder
  agent: >-
    processor

# create_graph:
#   description: >-
#     create a graph to represent the data in data.csv file stored in "D:\Projects\WhiteGlove\data_processing\src\output" folder
#   expected_output: >-
#     graph.jpg stored in "D:\Projects\WhiteGlove\data_processing\src\output" folder
#   agent: >-
#     graph_creator
