
read_pdf:
  description: >-
    read pdf file,
    for each electricity fact label or EFL,
    get  Company Name, Plan Name,  Base Charge and Energy Charge,
    make sure no plan is missed.
  expected_output: >-
    information of five plans as markdown
  agent: >-
    pdf_reader


get_relevant_data:
  description: >-
    Get Company Name, Plan Name,  Base Charge and Energy Charge charge for all companies and plans,
    enter 0 for unavailable charges,
    remove units and currency signs from base charge and energy charge,
    remove any commas(',') from Company Name and Plan Name.
  expected_output: >-
    Company name, plan name, base charge and energy charge
  agent: >-
    data_cleaner

write_to_file:
  description: >-
    write data to a output\plans.csv file, 
    overwrite if file already present.
  expected_output: >-
    plan.csv file with comma seperated data
  agent: >-
    data_writer

