
get_data:
  description: >-
    Browse https://sales.energysavings.com/plan-selection?zipCode=75252&promoCode=Default
    for every company get plan details  and write to markdown
  expected_output: >-
    Add your expected_output here
  agent: >-
    data_collector

# read_efl:
#   description: >-
#     write contents of 'efl' link ot a markdown
#   expected_output: >-
#     markdown information of efl or Electricity Facts Label
#   agent: >-
#     data_collector


get_relevant_data:
  description: >-
    get Company name, plan name, base charge and energy charge from Electricity Facts
    Label or EFL of different companies
  expected_output: >-
    Company name, plan name, and energy charge
  agent: >-
    data_analyzer

# write_to_file:
#   description: >-
#     append data to output/out.csv
#   expected_output: >-
#     out.csv file with extracted and analyzed data
#   agent: >-
#     data_writer

